/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UpgradeSuccessRouteImport } from './routes/upgrade_.success'
import { Route as UpgradeCompleteRouteImport } from './routes/upgrade_.complete'
import { Route as LoginCompleteRouteImport } from './routes/login_.complete'
import { Route as AccountCompleteRouteImport } from './routes/account_.complete'
import { Route as InvitationsTokenCompleteRouteImport } from './routes/invitations.$token.complete'
import { Route as InvitationsTokenAcceptRouteImport } from './routes/invitations.$token.accept'
import { Route as HostsHostIdWorkspacesRouteImport } from './routes/hosts.$hostId.workspaces'
import { Route as AccountOrganizationsOrgIdRouteImport } from './routes/account_.organizations.$orgId'
import { Route as HostsHostIdWorkspacesCreateRouteImport } from './routes/hosts.$hostId.workspaces_.create'
import { Route as HostsHostIdWorkspacesWorkspaceIdRouteImport } from './routes/hosts.$hostId.workspaces_.$workspaceId'
import { Route as HostsHostIdProjectsProjectIdRouteImport } from './routes/hosts.$hostId.projects.$projectId'
import { Route as HostsHostIdWorkspacesWorkspaceIdVscodeRouteImport } from './routes/hosts.$hostId.workspaces.$workspaceId.vscode'
import { Route as HostsHostIdProjectsProjectIdIssuesIssueIdRouteImport } from './routes/hosts.$hostId.projects.$projectId_.issues.$issueId'
import { Route as HostsHostIdProjectsProjectIdWorkspacesCreateDraftIdRouteImport } from './routes/hosts.$hostId.projects.$projectId_.workspaces.create.$draftId'
import { Route as HostsHostIdProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRouteImport } from './routes/hosts.$hostId.projects.$projectId_.issues.$issueId_.workspaces.$workspaceId'
import { Route as HostsHostIdProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRouteImport } from './routes/hosts.$hostId.projects.$projectId_.issues.$issueId_.workspaces.create.$draftId'

const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeSuccessRoute = UpgradeSuccessRouteImport.update({
  id: '/upgrade_/success',
  path: '/upgrade/success',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeCompleteRoute = UpgradeCompleteRouteImport.update({
  id: '/upgrade_/complete',
  path: '/upgrade/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginCompleteRoute = LoginCompleteRouteImport.update({
  id: '/login_/complete',
  path: '/login/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountCompleteRoute = AccountCompleteRouteImport.update({
  id: '/account_/complete',
  path: '/account/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsTokenCompleteRoute =
  InvitationsTokenCompleteRouteImport.update({
    id: '/invitations/$token/complete',
    path: '/invitations/$token/complete',
    getParentRoute: () => rootRouteImport,
  } as any)
const InvitationsTokenAcceptRoute = InvitationsTokenAcceptRouteImport.update({
  id: '/invitations/$token/accept',
  path: '/invitations/$token/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsHostIdWorkspacesRoute = HostsHostIdWorkspacesRouteImport.update({
  id: '/hosts/$hostId/workspaces',
  path: '/hosts/$hostId/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrganizationsOrgIdRoute =
  AccountOrganizationsOrgIdRouteImport.update({
    id: '/account_/organizations/$orgId',
    path: '/account/organizations/$orgId',
    getParentRoute: () => rootRouteImport,
  } as any)
const HostsHostIdWorkspacesCreateRoute =
  HostsHostIdWorkspacesCreateRouteImport.update({
    id: '/hosts/$hostId/workspaces_/create',
    path: '/hosts/$hostId/workspaces/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const HostsHostIdWorkspacesWorkspaceIdRoute =
  HostsHostIdWorkspacesWorkspaceIdRouteImport.update({
    id: '/hosts/$hostId/workspaces_/$workspaceId',
    path: '/hosts/$hostId/workspaces/$workspaceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const HostsHostIdProjectsProjectIdRoute =
  HostsHostIdProjectsProjectIdRouteImport.update({
    id: '/hosts/$hostId/projects/$projectId',
    path: '/hosts/$hostId/projects/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const HostsHostIdWorkspacesWorkspaceIdVscodeRoute =
  HostsHostIdWorkspacesWorkspaceIdVscodeRouteImport.update({
    id: '/$workspaceId/vscode',
    path: '/$workspaceId/vscode',
    getParentRoute: () => HostsHostIdWorkspacesRoute,
  } as any)
const HostsHostIdProjectsProjectIdIssuesIssueIdRoute =
  HostsHostIdProjectsProjectIdIssuesIssueIdRouteImport.update({
    id: '/hosts/$hostId/projects/$projectId_/issues/$issueId',
    path: '/hosts/$hostId/projects/$projectId/issues/$issueId',
    getParentRoute: () => rootRouteImport,
  } as any)
const HostsHostIdProjectsProjectIdWorkspacesCreateDraftIdRoute =
  HostsHostIdProjectsProjectIdWorkspacesCreateDraftIdRouteImport.update({
    id: '/hosts/$hostId/projects/$projectId_/workspaces/create/$draftId',
    path: '/hosts/$hostId/projects/$projectId/workspaces/create/$draftId',
    getParentRoute: () => rootRouteImport,
  } as any)
const HostsHostIdProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRoute =
  HostsHostIdProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRouteImport.update(
    {
      id: '/hosts/$hostId/projects/$projectId_/issues/$issueId_/workspaces/$workspaceId',
      path: '/hosts/$hostId/projects/$projectId/issues/$issueId/workspaces/$workspaceId',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const HostsHostIdProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRoute =
  HostsHostIdProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRouteImport.update(
    {
      id: '/hosts/$hostId/projects/$projectId_/issues/$issueId_/workspaces/create/$draftId',
      path: '/hosts/$hostId/projects/$projectId/issues/$issueId/workspaces/create/$draftId',
      getParentRoute: () => rootRouteImport,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/upgrade': typeof UpgradeRoute
  '/account/complete': typeof AccountCompleteRoute
  '/login/complete': typeof LoginCompleteRoute
  '/upgrade/complete': typeof UpgradeCompleteRoute
  '/upgrade/success': typeof UpgradeSuccessRoute
  '/account/organizations/$orgId': typeof AccountOrganizationsOrgIdRoute
  '/hosts/$hostId/workspaces': typeof HostsHostIdWorkspacesRouteWithChildren
  '/invitations/$token/accept': typeof InvitationsTokenAcceptRoute
  '/invitations/$token/complete': typeof InvitationsTokenCompleteRoute
  '/hosts/$hostId/projects/$projectId': typeof HostsHostIdProjectsProjectIdRoute
  '/hosts/$hostId/workspaces/$workspaceId': typeof HostsHostIdWorkspacesWorkspaceIdRoute
  '/hosts/$hostId/workspaces/create': typeof HostsHostIdWorkspacesCreateRoute
  '/hosts/$hostId/workspaces/$workspaceId/vscode': typeof HostsHostIdWorkspacesWorkspaceIdVscodeRoute
  '/hosts/$hostId/projects/$projectId/issues/$issueId': typeof HostsHostIdProjectsProjectIdIssuesIssueIdRoute
  '/hosts/$hostId/projects/$projectId/workspaces/create/$draftId': typeof HostsHostIdProjectsProjectIdWorkspacesCreateDraftIdRoute
  '/hosts/$hostId/projects/$projectId/issues/$issueId/workspaces/$workspaceId': typeof HostsHostIdProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRoute
  '/hosts/$hostId/projects/$projectId/issues/$issueId/workspaces/create/$draftId': typeof HostsHostIdProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/upgrade': typeof UpgradeRoute
  '/account/complete': typeof AccountCompleteRoute
  '/login/complete': typeof LoginCompleteRoute
  '/upgrade/complete': typeof UpgradeCompleteRoute
  '/upgrade/success': typeof UpgradeSuccessRoute
  '/account/organizations/$orgId': typeof AccountOrganizationsOrgIdRoute
  '/hosts/$hostId/workspaces': typeof HostsHostIdWorkspacesRouteWithChildren
  '/invitations/$token/accept': typeof InvitationsTokenAcceptRoute
  '/invitations/$token/complete': typeof InvitationsTokenCompleteRoute
  '/hosts/$hostId/projects/$projectId': typeof HostsHostIdProjectsProjectIdRoute
  '/hosts/$hostId/workspaces/$workspaceId': typeof HostsHostIdWorkspacesWorkspaceIdRoute
  '/hosts/$hostId/workspaces/create': typeof HostsHostIdWorkspacesCreateRoute
  '/hosts/$hostId/workspaces/$workspaceId/vscode': typeof HostsHostIdWorkspacesWorkspaceIdVscodeRoute
  '/hosts/$hostId/projects/$projectId/issues/$issueId': typeof HostsHostIdProjectsProjectIdIssuesIssueIdRoute
  '/hosts/$hostId/projects/$projectId/workspaces/create/$draftId': typeof HostsHostIdProjectsProjectIdWorkspacesCreateDraftIdRoute
  '/hosts/$hostId/projects/$projectId/issues/$issueId/workspaces/$workspaceId': typeof HostsHostIdProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRoute
  '/hosts/$hostId/projects/$projectId/issues/$issueId/workspaces/create/$draftId': typeof HostsHostIdProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/upgrade': typeof UpgradeRoute
  '/account_/complete': typeof AccountCompleteRoute
  '/login_/complete': typeof LoginCompleteRoute
  '/upgrade_/complete': typeof UpgradeCompleteRoute
  '/upgrade_/success': typeof UpgradeSuccessRoute
  '/account_/organizations/$orgId': typeof AccountOrganizationsOrgIdRoute
  '/hosts/$hostId/workspaces': typeof HostsHostIdWorkspacesRouteWithChildren
  '/invitations/$token/accept': typeof InvitationsTokenAcceptRoute
  '/invitations/$token/complete': typeof InvitationsTokenCompleteRoute
  '/hosts/$hostId/projects/$projectId': typeof HostsHostIdProjectsProjectIdRoute
  '/hosts/$hostId/workspaces_/$workspaceId': typeof HostsHostIdWorkspacesWorkspaceIdRoute
  '/hosts/$hostId/workspaces_/create': typeof HostsHostIdWorkspacesCreateRoute
  '/hosts/$hostId/workspaces/$workspaceId/vscode': typeof HostsHostIdWorkspacesWorkspaceIdVscodeRoute
  '/hosts/$hostId/projects/$projectId_/issues/$issueId': typeof HostsHostIdProjectsProjectIdIssuesIssueIdRoute
  '/hosts/$hostId/projects/$projectId_/workspaces/create/$draftId': typeof HostsHostIdProjectsProjectIdWorkspacesCreateDraftIdRoute
  '/hosts/$hostId/projects/$projectId_/issues/$issueId_/workspaces/$workspaceId': typeof HostsHostIdProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRoute
  '/hosts/$hostId/projects/$projectId_/issues/$issueId_/workspaces/create/$draftId': typeof HostsHostIdProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/login'
    | '/upgrade'
    | '/account/complete'
    | '/login/complete'
    | '/upgrade/complete'
    | '/upgrade/success'
    | '/account/organizations/$orgId'
    | '/hosts/$hostId/workspaces'
    | '/invitations/$token/accept'
    | '/invitations/$token/complete'
    | '/hosts/$hostId/projects/$projectId'
    | '/hosts/$hostId/workspaces/$workspaceId'
    | '/hosts/$hostId/workspaces/create'
    | '/hosts/$hostId/workspaces/$workspaceId/vscode'
    | '/hosts/$hostId/projects/$projectId/issues/$issueId'
    | '/hosts/$hostId/projects/$projectId/workspaces/create/$draftId'
    | '/hosts/$hostId/projects/$projectId/issues/$issueId/workspaces/$workspaceId'
    | '/hosts/$hostId/projects/$projectId/issues/$issueId/workspaces/create/$draftId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/login'
    | '/upgrade'
    | '/account/complete'
    | '/login/complete'
    | '/upgrade/complete'
    | '/upgrade/success'
    | '/account/organizations/$orgId'
    | '/hosts/$hostId/workspaces'
    | '/invitations/$token/accept'
    | '/invitations/$token/complete'
    | '/hosts/$hostId/projects/$projectId'
    | '/hosts/$hostId/workspaces/$workspaceId'
    | '/hosts/$hostId/workspaces/create'
    | '/hosts/$hostId/workspaces/$workspaceId/vscode'
    | '/hosts/$hostId/projects/$projectId/issues/$issueId'
    | '/hosts/$hostId/projects/$projectId/workspaces/create/$draftId'
    | '/hosts/$hostId/projects/$projectId/issues/$issueId/workspaces/$workspaceId'
    | '/hosts/$hostId/projects/$projectId/issues/$issueId/workspaces/create/$draftId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/login'
    | '/upgrade'
    | '/account_/complete'
    | '/login_/complete'
    | '/upgrade_/complete'
    | '/upgrade_/success'
    | '/account_/organizations/$orgId'
    | '/hosts/$hostId/workspaces'
    | '/invitations/$token/accept'
    | '/invitations/$token/complete'
    | '/hosts/$hostId/projects/$projectId'
    | '/hosts/$hostId/workspaces_/$workspaceId'
    | '/hosts/$hostId/workspaces_/create'
    | '/hosts/$hostId/workspaces/$workspaceId/vscode'
    | '/hosts/$hostId/projects/$projectId_/issues/$issueId'
    | '/hosts/$hostId/projects/$projectId_/workspaces/create/$draftId'
    | '/hosts/$hostId/projects/$projectId_/issues/$issueId_/workspaces/$workspaceId'
    | '/hosts/$hostId/projects/$projectId_/issues/$issueId_/workspaces/create/$draftId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  LoginRoute: typeof LoginRoute
  UpgradeRoute: typeof UpgradeRoute
  AccountCompleteRoute: typeof AccountCompleteRoute
  LoginCompleteRoute: typeof LoginCompleteRoute
  UpgradeCompleteRoute: typeof UpgradeCompleteRoute
  UpgradeSuccessRoute: typeof UpgradeSuccessRoute
  AccountOrganizationsOrgIdRoute: typeof AccountOrganizationsOrgIdRoute
  HostsHostIdWorkspacesRoute: typeof HostsHostIdWorkspacesRouteWithChildren
  InvitationsTokenAcceptRoute: typeof InvitationsTokenAcceptRoute
  InvitationsTokenCompleteRoute: typeof InvitationsTokenCompleteRoute
  HostsHostIdProjectsProjectIdRoute: typeof HostsHostIdProjectsProjectIdRoute
  HostsHostIdWorkspacesWorkspaceIdRoute: typeof HostsHostIdWorkspacesWorkspaceIdRoute
  HostsHostIdWorkspacesCreateRoute: typeof HostsHostIdWorkspacesCreateRoute
  HostsHostIdProjectsProjectIdIssuesIssueIdRoute: typeof HostsHostIdProjectsProjectIdIssuesIssueIdRoute
  HostsHostIdProjectsProjectIdWorkspacesCreateDraftIdRoute: typeof HostsHostIdProjectsProjectIdWorkspacesCreateDraftIdRoute
  HostsHostIdProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRoute: typeof HostsHostIdProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRoute
  HostsHostIdProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRoute: typeof HostsHostIdProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade_/success': {
      id: '/upgrade_/success'
      path: '/upgrade/success'
      fullPath: '/upgrade/success'
      preLoaderRoute: typeof UpgradeSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade_/complete': {
      id: '/upgrade_/complete'
      path: '/upgrade/complete'
      fullPath: '/upgrade/complete'
      preLoaderRoute: typeof UpgradeCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login_/complete': {
      id: '/login_/complete'
      path: '/login/complete'
      fullPath: '/login/complete'
      preLoaderRoute: typeof LoginCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/complete': {
      id: '/account_/complete'
      path: '/account/complete'
      fullPath: '/account/complete'
      preLoaderRoute: typeof AccountCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/$token/complete': {
      id: '/invitations/$token/complete'
      path: '/invitations/$token/complete'
      fullPath: '/invitations/$token/complete'
      preLoaderRoute: typeof InvitationsTokenCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/$token/accept': {
      id: '/invitations/$token/accept'
      path: '/invitations/$token/accept'
      fullPath: '/invitations/$token/accept'
      preLoaderRoute: typeof InvitationsTokenAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/$hostId/workspaces': {
      id: '/hosts/$hostId/workspaces'
      path: '/hosts/$hostId/workspaces'
      fullPath: '/hosts/$hostId/workspaces'
      preLoaderRoute: typeof HostsHostIdWorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/organizations/$orgId': {
      id: '/account_/organizations/$orgId'
      path: '/account/organizations/$orgId'
      fullPath: '/account/organizations/$orgId'
      preLoaderRoute: typeof AccountOrganizationsOrgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/$hostId/workspaces_/create': {
      id: '/hosts/$hostId/workspaces_/create'
      path: '/hosts/$hostId/workspaces/create'
      fullPath: '/hosts/$hostId/workspaces/create'
      preLoaderRoute: typeof HostsHostIdWorkspacesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/$hostId/workspaces_/$workspaceId': {
      id: '/hosts/$hostId/workspaces_/$workspaceId'
      path: '/hosts/$hostId/workspaces/$workspaceId'
      fullPath: '/hosts/$hostId/workspaces/$workspaceId'
      preLoaderRoute: typeof HostsHostIdWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/$hostId/projects/$projectId': {
      id: '/hosts/$hostId/projects/$projectId'
      path: '/hosts/$hostId/projects/$projectId'
      fullPath: '/hosts/$hostId/projects/$projectId'
      preLoaderRoute: typeof HostsHostIdProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/$hostId/workspaces/$workspaceId/vscode': {
      id: '/hosts/$hostId/workspaces/$workspaceId/vscode'
      path: '/$workspaceId/vscode'
      fullPath: '/hosts/$hostId/workspaces/$workspaceId/vscode'
      preLoaderRoute: typeof HostsHostIdWorkspacesWorkspaceIdVscodeRouteImport
      parentRoute: typeof HostsHostIdWorkspacesRoute
    }
    '/hosts/$hostId/projects/$projectId_/issues/$issueId': {
      id: '/hosts/$hostId/projects/$projectId_/issues/$issueId'
      path: '/hosts/$hostId/projects/$projectId/issues/$issueId'
      fullPath: '/hosts/$hostId/projects/$projectId/issues/$issueId'
      preLoaderRoute: typeof HostsHostIdProjectsProjectIdIssuesIssueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/$hostId/projects/$projectId_/workspaces/create/$draftId': {
      id: '/hosts/$hostId/projects/$projectId_/workspaces/create/$draftId'
      path: '/hosts/$hostId/projects/$projectId/workspaces/create/$draftId'
      fullPath: '/hosts/$hostId/projects/$projectId/workspaces/create/$draftId'
      preLoaderRoute: typeof HostsHostIdProjectsProjectIdWorkspacesCreateDraftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/$hostId/projects/$projectId_/issues/$issueId_/workspaces/$workspaceId': {
      id: '/hosts/$hostId/projects/$projectId_/issues/$issueId_/workspaces/$workspaceId'
      path: '/hosts/$hostId/projects/$projectId/issues/$issueId/workspaces/$workspaceId'
      fullPath: '/hosts/$hostId/projects/$projectId/issues/$issueId/workspaces/$workspaceId'
      preLoaderRoute: typeof HostsHostIdProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/$hostId/projects/$projectId_/issues/$issueId_/workspaces/create/$draftId': {
      id: '/hosts/$hostId/projects/$projectId_/issues/$issueId_/workspaces/create/$draftId'
      path: '/hosts/$hostId/projects/$projectId/issues/$issueId/workspaces/create/$draftId'
      fullPath: '/hosts/$hostId/projects/$projectId/issues/$issueId/workspaces/create/$draftId'
      preLoaderRoute: typeof HostsHostIdProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HostsHostIdWorkspacesRouteChildren {
  HostsHostIdWorkspacesWorkspaceIdVscodeRoute: typeof HostsHostIdWorkspacesWorkspaceIdVscodeRoute
}

const HostsHostIdWorkspacesRouteChildren: HostsHostIdWorkspacesRouteChildren = {
  HostsHostIdWorkspacesWorkspaceIdVscodeRoute:
    HostsHostIdWorkspacesWorkspaceIdVscodeRoute,
}

const HostsHostIdWorkspacesRouteWithChildren =
  HostsHostIdWorkspacesRoute._addFileChildren(
    HostsHostIdWorkspacesRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  LoginRoute: LoginRoute,
  UpgradeRoute: UpgradeRoute,
  AccountCompleteRoute: AccountCompleteRoute,
  LoginCompleteRoute: LoginCompleteRoute,
  UpgradeCompleteRoute: UpgradeCompleteRoute,
  UpgradeSuccessRoute: UpgradeSuccessRoute,
  AccountOrganizationsOrgIdRoute: AccountOrganizationsOrgIdRoute,
  HostsHostIdWorkspacesRoute: HostsHostIdWorkspacesRouteWithChildren,
  InvitationsTokenAcceptRoute: InvitationsTokenAcceptRoute,
  InvitationsTokenCompleteRoute: InvitationsTokenCompleteRoute,
  HostsHostIdProjectsProjectIdRoute: HostsHostIdProjectsProjectIdRoute,
  HostsHostIdWorkspacesWorkspaceIdRoute: HostsHostIdWorkspacesWorkspaceIdRoute,
  HostsHostIdWorkspacesCreateRoute: HostsHostIdWorkspacesCreateRoute,
  HostsHostIdProjectsProjectIdIssuesIssueIdRoute:
    HostsHostIdProjectsProjectIdIssuesIssueIdRoute,
  HostsHostIdProjectsProjectIdWorkspacesCreateDraftIdRoute:
    HostsHostIdProjectsProjectIdWorkspacesCreateDraftIdRoute,
  HostsHostIdProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRoute:
    HostsHostIdProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRoute,
  HostsHostIdProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRoute:
    HostsHostIdProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
