/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UpgradeSuccessRouteImport } from './routes/upgrade_.success'
import { Route as UpgradeCompleteRouteImport } from './routes/upgrade_.complete'
import { Route as ReviewIdRouteImport } from './routes/review.$id'
import { Route as AccountCompleteRouteImport } from './routes/account_.complete'
import { Route as InvitationsTokenCompleteRouteImport } from './routes/invitations.$token.complete'
import { Route as InvitationsTokenAcceptRouteImport } from './routes/invitations.$token.accept'
import { Route as AccountOrganizationsOrgIdRouteImport } from './routes/account_.organizations.$orgId'

const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeSuccessRoute = UpgradeSuccessRouteImport.update({
  id: '/upgrade_/success',
  path: '/upgrade/success',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeCompleteRoute = UpgradeCompleteRouteImport.update({
  id: '/upgrade_/complete',
  path: '/upgrade/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewIdRoute = ReviewIdRouteImport.update({
  id: '/review/$id',
  path: '/review/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountCompleteRoute = AccountCompleteRouteImport.update({
  id: '/account_/complete',
  path: '/account/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsTokenCompleteRoute =
  InvitationsTokenCompleteRouteImport.update({
    id: '/invitations/$token/complete',
    path: '/invitations/$token/complete',
    getParentRoute: () => rootRouteImport,
  } as any)
const InvitationsTokenAcceptRoute = InvitationsTokenAcceptRouteImport.update({
  id: '/invitations/$token/accept',
  path: '/invitations/$token/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrganizationsOrgIdRoute =
  AccountOrganizationsOrgIdRouteImport.update({
    id: '/account_/organizations/$orgId',
    path: '/account/organizations/$orgId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/upgrade': typeof UpgradeRoute
  '/account/complete': typeof AccountCompleteRoute
  '/review/$id': typeof ReviewIdRoute
  '/upgrade/complete': typeof UpgradeCompleteRoute
  '/upgrade/success': typeof UpgradeSuccessRoute
  '/account/organizations/$orgId': typeof AccountOrganizationsOrgIdRoute
  '/invitations/$token/accept': typeof InvitationsTokenAcceptRoute
  '/invitations/$token/complete': typeof InvitationsTokenCompleteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/upgrade': typeof UpgradeRoute
  '/account/complete': typeof AccountCompleteRoute
  '/review/$id': typeof ReviewIdRoute
  '/upgrade/complete': typeof UpgradeCompleteRoute
  '/upgrade/success': typeof UpgradeSuccessRoute
  '/account/organizations/$orgId': typeof AccountOrganizationsOrgIdRoute
  '/invitations/$token/accept': typeof InvitationsTokenAcceptRoute
  '/invitations/$token/complete': typeof InvitationsTokenCompleteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/upgrade': typeof UpgradeRoute
  '/account_/complete': typeof AccountCompleteRoute
  '/review/$id': typeof ReviewIdRoute
  '/upgrade_/complete': typeof UpgradeCompleteRoute
  '/upgrade_/success': typeof UpgradeSuccessRoute
  '/account_/organizations/$orgId': typeof AccountOrganizationsOrgIdRoute
  '/invitations/$token/accept': typeof InvitationsTokenAcceptRoute
  '/invitations/$token/complete': typeof InvitationsTokenCompleteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/upgrade'
    | '/account/complete'
    | '/review/$id'
    | '/upgrade/complete'
    | '/upgrade/success'
    | '/account/organizations/$orgId'
    | '/invitations/$token/accept'
    | '/invitations/$token/complete'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/upgrade'
    | '/account/complete'
    | '/review/$id'
    | '/upgrade/complete'
    | '/upgrade/success'
    | '/account/organizations/$orgId'
    | '/invitations/$token/accept'
    | '/invitations/$token/complete'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/upgrade'
    | '/account_/complete'
    | '/review/$id'
    | '/upgrade_/complete'
    | '/upgrade_/success'
    | '/account_/organizations/$orgId'
    | '/invitations/$token/accept'
    | '/invitations/$token/complete'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  UpgradeRoute: typeof UpgradeRoute
  AccountCompleteRoute: typeof AccountCompleteRoute
  ReviewIdRoute: typeof ReviewIdRoute
  UpgradeCompleteRoute: typeof UpgradeCompleteRoute
  UpgradeSuccessRoute: typeof UpgradeSuccessRoute
  AccountOrganizationsOrgIdRoute: typeof AccountOrganizationsOrgIdRoute
  InvitationsTokenAcceptRoute: typeof InvitationsTokenAcceptRoute
  InvitationsTokenCompleteRoute: typeof InvitationsTokenCompleteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade_/success': {
      id: '/upgrade_/success'
      path: '/upgrade/success'
      fullPath: '/upgrade/success'
      preLoaderRoute: typeof UpgradeSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade_/complete': {
      id: '/upgrade_/complete'
      path: '/upgrade/complete'
      fullPath: '/upgrade/complete'
      preLoaderRoute: typeof UpgradeCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$id': {
      id: '/review/$id'
      path: '/review/$id'
      fullPath: '/review/$id'
      preLoaderRoute: typeof ReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/complete': {
      id: '/account_/complete'
      path: '/account/complete'
      fullPath: '/account/complete'
      preLoaderRoute: typeof AccountCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/$token/complete': {
      id: '/invitations/$token/complete'
      path: '/invitations/$token/complete'
      fullPath: '/invitations/$token/complete'
      preLoaderRoute: typeof InvitationsTokenCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/$token/accept': {
      id: '/invitations/$token/accept'
      path: '/invitations/$token/accept'
      fullPath: '/invitations/$token/accept'
      preLoaderRoute: typeof InvitationsTokenAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/organizations/$orgId': {
      id: '/account_/organizations/$orgId'
      path: '/account/organizations/$orgId'
      fullPath: '/account/organizations/$orgId'
      preLoaderRoute: typeof AccountOrganizationsOrgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  UpgradeRoute: UpgradeRoute,
  AccountCompleteRoute: AccountCompleteRoute,
  ReviewIdRoute: ReviewIdRoute,
  UpgradeCompleteRoute: UpgradeCompleteRoute,
  UpgradeSuccessRoute: UpgradeSuccessRoute,
  AccountOrganizationsOrgIdRoute: AccountOrganizationsOrgIdRoute,
  InvitationsTokenAcceptRoute: InvitationsTokenAcceptRoute,
  InvitationsTokenCompleteRoute: InvitationsTokenCompleteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
