import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@vibe/ui/components/KeyboardDialog';
import { Label } from '@radix-ui/react-label';
import { Textarea } from '@vibe/ui/components/Textarea';
import { Button } from '@vibe/ui/components/Button';
import { Input } from '@vibe/ui/components/Input';
import { Checkbox } from '@vibe/ui/components/Checkbox';
import { Alert, AlertDescription, AlertTitle } from '@vibe/ui/components/Alert';
import BranchSelector from '@/shared/components/tasks/BranchSelector';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { workspacesApi } from '@/shared/lib/api';
import { useTranslation } from 'react-i18next';

import { Workspace } from 'shared/types';
import { Loader2 } from 'lucide-react';
import { create, useModal } from '@ebay/nice-modal-react';
import { useAuth } from '@/shared/hooks/auth/useAuth';
import { useRepoBranches } from '@/shared/hooks/useRepoBranches';
import {
  GhCliHelpInstructions,
  GhCliSetupDialog,
  mapGhCliErrorToUi,
} from '@/shared/dialogs/auth/GhCliSetupDialog';
import type {
  GhCliSupportContent,
  GhCliSupportVariant,
} from '@/shared/dialogs/auth/GhCliSetupDialog';
import type { GhCliSetupError } from 'shared/types';
import { useUserSystem } from '@/shared/hooks/useUserSystem';
import { defineModal } from '@/shared/lib/modals';
import { splitMessageToTitleDescription } from '@/shared/lib/string';

interface CreatePRDialogProps {
  attempt: Workspace;
  repoId: string;
  targetBranch?: string;
  /**
   * Default head (source) branch — typically an intermediate "feature" branch
   * the work branch was merged into (three-branch workflow). Falls back to the
   * workspace's work branch when absent or not found in the branch list.
   */
  headBranch?: string;
  /**
   * Fallback base branch (repo's default target) used when no remembered choice
   * exists and the head is a feature branch (so `targetBranch` would be wrong).
   */
  defaultBaseBranch?: string;
  issueIdentifier?: string;
}

export type CreatePRDialogResult = {
  success: boolean;
  error?: string;
};

const PR_TITLE_SUFFIX = ' (vibe-kanban)';

// Remember the last base branch the user actually opened a PR against, per repo,
// so the next PR (e.g. feature -> develop) defaults to the same base.
const prBaseStorageKey = (repoId: string) => `vk-pr-base:${repoId}`;

const readRememberedBase = (repoId: string): string | undefined => {
  try {
    return localStorage.getItem(prBaseStorageKey(repoId)) ?? undefined;
  } catch {
    return undefined;
  }
};

const rememberBase = (repoId: string, base: string) => {
  try {
    if (base) localStorage.setItem(prBaseStorageKey(repoId), base);
  } catch {
    // localStorage may be unavailable (private mode); remembering is best-effort.
  }
};

const appendPrTitleSuffix = (title: string): string => {
  const trimmedTitle = title.trim();
  if (!trimmedTitle) return trimmedTitle;
  if (trimmedTitle.endsWith(PR_TITLE_SUFFIX)) return trimmedTitle;
  return `${trimmedTitle}${PR_TITLE_SUFFIX}`;
};

const CreatePRDialogImpl = create<CreatePRDialogProps>(
  ({
    attempt,
    repoId,
    targetBranch,
    headBranch,
    defaultBaseBranch,
    issueIdentifier,
  }) => {
    const modal = useModal();
    const { t } = useTranslation('tasks');
    const { isLoaded } = useAuth();
    const { environment, config } = useUserSystem();
    const [prTitle, setPrTitle] = useState('');
    const [prBody, setPrBody] = useState('');
    const [prHeadBranch, setPrHeadBranch] = useState('');
    const [prBaseBranch, setPrBaseBranch] = useState('');
    const [creatingPR, setCreatingPR] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [ghCliHelp, setGhCliHelp] = useState<GhCliSupportContent | null>(
      null
    );
    const [isDraft, setIsDraft] = useState(false);
    const [autoGenerateDescription, setAutoGenerateDescription] = useState(
      config?.pr_auto_description_enabled ?? false
    );
    const resetFormState = useCallback(() => {
      setPrTitle('');
      setPrBody('');
      setPrHeadBranch('');
      setPrBaseBranch('');
      setCreatingPR(false);
      setError(null);
      setGhCliHelp(null);
      setIsDraft(false);
      setAutoGenerateDescription(config?.pr_auto_description_enabled ?? false);
    }, [config?.pr_auto_description_enabled]);

    const { data: branches = [], isLoading: branchesLoading } = useRepoBranches(
      repoId,
      { enabled: modal.visible && !!repoId }
    );

    useEffect(() => {
      if (!modal.visible) {
        resetFormState();
      }
    }, [modal.visible, resetFormState]);

    const getGhCliHelpTitle = (variant: GhCliSupportVariant) =>
      variant === 'homebrew'
        ? 'Homebrew is required for automatic setup'
        : 'GitHub CLI needs manual setup';

    // Initialize form when dialog opens
    useEffect(() => {
      if (!modal.visible || !isLoaded) {
        return;
      }

      let isCancelled = false;

      const initializePRFields = async () => {
        try {
          const firstUserMessage = await workspacesApi.getFirstUserMessage(
            attempt.id
          );

          if (isCancelled) return;

          if (firstUserMessage?.trim()) {
            const { title, description } =
              splitMessageToTitleDescription(firstUserMessage);
            setPrTitle(appendPrTitleSuffix(title));
            setPrBody(description ?? '');
            return;
          }
        } catch {
          // Fall back to empty fields if prompt loading fails.
        }

        if (isCancelled) return;
        setPrTitle('');
        setPrBody('');
      };

      initializePRFields();
      setError(null);
      setGhCliHelp(null);

      return () => {
        isCancelled = true;
      };
    }, [attempt.id, modal.visible, isLoaded, issueIdentifier]);

    // Set default head (source) branch when branches load. Prefer the feature
    // branch the work branch was merged into; fall back to the work branch.
    useEffect(() => {
      if (!modal.visible || branches.length === 0) {
        return;
      }
      const exists = (name: string) =>
        branches.some((branch) => branch.name === name);
      if (prHeadBranch && exists(prHeadBranch)) {
        return;
      }
      const desired =
        headBranch && exists(headBranch) ? headBranch : attempt.branch;
      setPrHeadBranch(exists(desired) ? desired : '');
    }, [branches, modal.visible, prHeadBranch, headBranch, attempt.branch]);

    // Set default base branch when branches/head load. Candidates, best first:
    // a remembered choice, the workspace's current target (only when the head is
    // the work branch — for a feature head the target branch IS the head, so it's
    // skipped), then the repo default. Never default the base to the head branch.
    useEffect(() => {
      if (!modal.visible || branches.length === 0) {
        return;
      }
      const exists = (name: string) =>
        branches.some((branch) => branch.name === name);
      const hasValidSelection =
        prBaseBranch && exists(prBaseBranch) && prBaseBranch !== prHeadBranch;
      if (hasValidSelection) {
        return;
      }
      const candidates = [
        readRememberedBase(repoId),
        // For a work-branch head, the workspace's explicitly chosen merge target
        // is the most accurate base. For a feature head the target IS the head,
        // so it's skipped here and the repo default is used instead.
        prHeadBranch === attempt.branch ? targetBranch : undefined,
        defaultBaseBranch ?? undefined,
      ];
      const pick = candidates.find(
        (c): c is string => !!c && exists(c) && c !== prHeadBranch
      );
      // Leave empty when nothing resolves; backend falls back to repo target branch.
      setPrBaseBranch(pick ?? '');
    }, [
      branches,
      modal.visible,
      prBaseBranch,
      prHeadBranch,
      repoId,
      defaultBaseBranch,
      targetBranch,
      attempt.branch,
    ]);

    const isMacEnvironment = useMemo(
      () => environment?.os_type?.toLowerCase().includes('mac'),
      [environment?.os_type]
    );

    const handleConfirmCreatePR = useCallback(async () => {
      if (!repoId || !attempt.id) return;

      setError(null);
      setGhCliHelp(null);
      setCreatingPR(true);

      const handleGhCliSetupOutcome = (
        setupResult: GhCliSetupError | null,
        fallbackMessage: string
      ) => {
        if (setupResult === null) {
          setError(null);
          setGhCliHelp(null);
          setCreatingPR(false);
          modal.hide();
          return;
        }

        const ui = mapGhCliErrorToUi(setupResult, fallbackMessage, t);

        if (ui.variant) {
          setGhCliHelp(ui);
          setError(null);
          return;
        }

        setGhCliHelp(null);
        setError(ui.message);
      };

      let result: Awaited<ReturnType<typeof workspacesApi.createPR>>;
      try {
        result = await workspacesApi.createPR(attempt.id, {
          title: prTitle,
          body: prBody || null,
          target_branch: prBaseBranch || null,
          head_branch: prHeadBranch || null,
          draft: isDraft,
          auto_generate_description: autoGenerateDescription,
          repo_id: repoId,
        });
      } catch (err) {
        // Without this guard a rejected createPR (network/unexpected error)
        // would skip the setCreatingPR(false) calls below, leaving the dialog
        // stuck with its submit button disabled, plus an unhandled rejection.
        setCreatingPR(false);
        setGhCliHelp(null);
        setError(
          err instanceof Error
            ? err.message
            : t('createPrDialog.errors.failedToCreate')
        );
        return;
      }

      if (result.success) {
        // Remember the base for next time (per repo) now that it succeeded.
        if (prBaseBranch) rememberBase(repoId, prBaseBranch);
        setCreatingPR(false);
        modal.resolve({ success: true } as CreatePRDialogResult);
        modal.hide();
        return;
      }

      setCreatingPR(false);

      const defaultGhCliErrorMessage =
        result.message || 'Failed to run GitHub CLI setup.';

      const showGhCliSetupDialog = async () => {
        const setupResult = await GhCliSetupDialog.show({
          workspaceId: attempt.id,
        });

        handleGhCliSetupOutcome(setupResult, defaultGhCliErrorMessage);
      };

      if (result.error) {
        if (
          result.error.type === 'cli_not_installed' ||
          result.error.type === 'cli_not_logged_in'
        ) {
          // Only show setup dialog for GitHub CLI on Mac
          if (result.error.provider === 'git_hub' && isMacEnvironment) {
            await showGhCliSetupDialog();
          } else {
            const providerName =
              result.error.provider === 'git_hub'
                ? 'GitHub'
                : result.error.provider === 'azure_dev_ops'
                  ? 'Azure DevOps'
                  : 'Git host';
            const action =
              result.error.type === 'cli_not_installed'
                ? 'not installed'
                : 'not logged in';
            setError(`${providerName} CLI is ${action}`);
            setGhCliHelp(null);
          }
          return;
        } else if (
          result.error.type === 'git_cli_not_installed' ||
          result.error.type === 'git_cli_not_logged_in'
        ) {
          const gitCliErrorKey =
            result.error.type === 'git_cli_not_logged_in'
              ? 'createPrDialog.errors.gitCliNotLoggedIn'
              : 'createPrDialog.errors.gitCliNotInstalled';

          setError(result.message || t(gitCliErrorKey));
          setGhCliHelp(null);
          return;
        } else if (result.error.type === 'target_branch_not_found') {
          setError(
            t('createPrDialog.errors.targetBranchNotFound', {
              branch: result.error.branch,
            })
          );
          setGhCliHelp(null);
          return;
        }
      }

      if (result.message) {
        setError(result.message);
        setGhCliHelp(null);
      } else {
        setError(t('createPrDialog.errors.failedToCreate'));
        setGhCliHelp(null);
      }
    }, [
      attempt,
      repoId,
      prHeadBranch,
      prBaseBranch,
      prBody,
      prTitle,
      isDraft,
      autoGenerateDescription,
      config?.pr_auto_description_enabled,
      modal,
      isMacEnvironment,
      t,
    ]);

    const handleCancelCreatePR = useCallback(() => {
      // Return error if one was set, otherwise just canceled
      const result: CreatePRDialogResult = error
        ? { success: false, error }
        : { success: false };
      modal.resolve(result);
      modal.hide();
    }, [modal, error]);

    return (
      <>
        <Dialog
          open={modal.visible}
          onOpenChange={(open) => {
            if (!open) {
              handleCancelCreatePR();
            }
          }}
        >
          <DialogContent className="sm:max-w-[525px]">
            <DialogHeader>
              <DialogTitle>{t('createPrDialog.title')}</DialogTitle>
              <DialogDescription>
                {t('createPrDialog.description')}
              </DialogDescription>
            </DialogHeader>
            {!isLoaded ? (
              <div className="flex justify-center py-8">
                <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
              </div>
            ) : (
              <div className="space-y-4 py-4">
                <div className="flex items-center space-x-2">
                  <Checkbox
                    id="pr-auto-generate"
                    checked={autoGenerateDescription}
                    onCheckedChange={setAutoGenerateDescription}
                    className="h-5 w-5"
                  />
                  <Label
                    htmlFor="pr-auto-generate"
                    className="cursor-pointer text-sm"
                  >
                    {t('createPrDialog.autoGenerateLabel')}
                  </Label>
                </div>
                <div className="space-y-2">
                  <Label htmlFor="pr-title">
                    {t('createPrDialog.titleLabel')}
                  </Label>
                  <Input
                    id="pr-title"
                    value={prTitle}
                    onChange={(e) => setPrTitle(e.target.value)}
                    onKeyDown={(e) => {
                      if (
                        e.key === 'Enter' &&
                        !e.nativeEvent.isComposing &&
                        prTitle.trim() &&
                        !creatingPR
                      ) {
                        e.preventDefault();
                        handleConfirmCreatePR();
                      }
                    }}
                    placeholder={t('createPrDialog.titlePlaceholder')}
                    disabled={autoGenerateDescription}
                    className={
                      autoGenerateDescription
                        ? 'opacity-50 cursor-not-allowed'
                        : ''
                    }
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="pr-body">
                    {t('createPrDialog.descriptionLabel')}
                  </Label>
                  <Textarea
                    id="pr-body"
                    value={prBody}
                    onChange={(e) => setPrBody(e.target.value)}
                    placeholder={t('createPrDialog.descriptionPlaceholder')}
                    rows={4}
                    disabled={autoGenerateDescription}
                    className={
                      autoGenerateDescription
                        ? 'opacity-50 cursor-not-allowed'
                        : ''
                    }
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="pr-head">
                    {t('createPrDialog.headBranchLabel')}
                  </Label>
                  <BranchSelector
                    branches={branches}
                    selectedBranch={prHeadBranch}
                    onBranchSelect={setPrHeadBranch}
                    placeholder={
                      branchesLoading
                        ? t('createPrDialog.loadingBranches')
                        : t('createPrDialog.selectHeadBranch')
                    }
                    className={
                      branchesLoading ? 'opacity-50 cursor-not-allowed' : ''
                    }
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="pr-base">
                    {t('createPrDialog.baseBranchLabel')}
                  </Label>
                  <BranchSelector
                    branches={branches}
                    selectedBranch={prBaseBranch}
                    onBranchSelect={setPrBaseBranch}
                    placeholder={
                      branchesLoading
                        ? t('createPrDialog.loadingBranches')
                        : t('createPrDialog.selectBaseBranch')
                    }
                    className={
                      branchesLoading ? 'opacity-50 cursor-not-allowed' : ''
                    }
                  />
                </div>
                <div className="flex items-center space-x-2">
                  <Checkbox
                    id="pr-draft"
                    checked={isDraft}
                    onCheckedChange={setIsDraft}
                    className="h-5 w-5"
                  />
                  <Label htmlFor="pr-draft" className="cursor-pointer text-sm">
                    {t('createPrDialog.draftLabel')}
                  </Label>
                </div>
                {ghCliHelp?.variant && (
                  <Alert variant="default">
                    <AlertTitle>
                      {getGhCliHelpTitle(ghCliHelp.variant)}
                    </AlertTitle>
                    <AlertDescription className="space-y-3">
                      <p>{ghCliHelp.message}</p>
                      <GhCliHelpInstructions
                        variant={ghCliHelp.variant}
                        t={t}
                      />
                    </AlertDescription>
                  </Alert>
                )}
                {error && <Alert variant="destructive">{error}</Alert>}
              </div>
            )}
            <DialogFooter>
              <Button
                type="button"
                variant="outline"
                onClick={handleCancelCreatePR}
              >
                {t('common:buttons.cancel')}
              </Button>
              <Button
                type="submit"
                onClick={handleConfirmCreatePR}
                disabled={creatingPR || !prTitle.trim()}
                className="bg-blue-600 hover:bg-blue-700"
              >
                {creatingPR ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    {t('createPrDialog.creating')}
                  </>
                ) : (
                  t('createPrDialog.createButton')
                )}
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </>
    );
  }
);

export const CreatePRDialog = defineModal<
  CreatePRDialogProps,
  CreatePRDialogResult
>(CreatePRDialogImpl);
