export {
  pruneUndefinedSearch,
  searchParamsToKanbanSearch,
  toMigrate,
  toOnboarding,
  toOnboardingSignIn,
  toProject,
  toProjectIssue,
  toProjectIssueCreate,
  toProjectIssueWorkspace,
  toProjectIssueWorkspaceCreate,
  toProjectWorkspaceCreate,
  toRoot,
  toWorkspace,
  toWorkspaceVsCode,
  toWorkspaces,
  toWorkspacesCreate,
  type ProjectKanbanSearch,
} from '@/shared/lib/routes/navigation';
